Ado 3835 vignettes
2DegreesInvesting/r2dii.climate.stress.test pull request #317
Opened 2022-02-01 12:20 UTC by MirijaHa

2022-02-01 14:44 UTC, jakubcervenka commented
otherwise LGTM

2022-02-01 16:31 UTC, jacobvjk approved these changes
@jakubcervenka is surely more qualified than me to judge if this is a helpful vignette. Assuming he is fine with it, this LGTM

2022-02-02 10:01 UTC, jakubcervenka approved these changes

2022-02-02 10:01 UTC, jakubcervenka commented
Like this pls:

company_name: character, holding the name of analysed companies
company_id: numeric, the id of company as classified by asset resolution. For loans workflow a placeholder value will be used.
corporate_bond_ticker: character, holding the identifier. Will be NA for loans workflow.
pd: numeric, holding the probability of default per company. Needs to be equal to or larger than 0 and smaller than 1.
net_profit_margin: numeric, holding the net_profit_margin per company. Needs to be larger than 0 and equal to or smaller than 1.
debt_equity_ratio: numeric, holding the ratio of outstanding debt to the company’s equity value. This is the leverage. Needs to be larger than 0.
volatility: numeric, holding the volatility of asset. Needs to be equal to or larger than 0.

2022-02-02 10:10 UTC, jakubcervenka requested changes

2022-02-02 10:10 UTC, jakubcervenka commented on vignettes/articles/04-advanced-data-settings.Rmd
>  * `company_id`: numeric, id of company as classified by asset resolution. For
Like this pls:

company_name: character, holding the name of analysed companies
company_id: numeric, the id of company as classified by asset resolution. For loans workflow a placeholder value will be used.
corporate_bond_ticker: character, holding the identifier. Will be NA for loans workflow.
pd: numeric, holding the probability of default per company. Needs to be equal to or larger than 0 and smaller than 1.
net_profit_margin: numeric, holding the net_profit_margin per company. Needs to be larger than 0 and equal to or smaller than 1.
debt_equity_ratio: numeric, holding the ratio of outstanding debt to the company’s equity value. This is the leverage. Needs to be larger than 0.
volatility: numeric, holding the volatility of asset. Needs to be equal to or larger than 0.

2022-02-02 11:56 UTC, jakubcervenka approved these changes

2022-02-02 11:56 UTC, jakubcervenka commented
Feel free to merge

2022-02-02 12:35 UTC, merged