Vignettes contacts
2DegreesInvesting/r2dii.climate.stress.test pull request #396
Opened 2022-05-25 14:55 UTC by jakubcervenka

just changing two instances of jacob@.... to stresstest@...
I have not touched the DESCRIPTION coz I don't know how to edit but not as important probably

2022-05-27 08:47 UTC, jacobvjk reviewed
lgtm, but @MirijaHa please check if you are fine with it too

2022-05-31 07:40 UTC, MirijaHa approved these changes

2022-05-31 07:41 UTC, MirijaHa commented
suggestion: before jacob leaves we have to update the contact author in the desciption. Could also do that now, simply exchange given and email with 2dii info and make sure to leave roles as they are, e.g. as done here: https://github.com/2DegreesInvesting/r2dii.analysis/blob/96d3965d68e1dedbd9e4ddcfca57857dc8590c67/DESCRIPTION#L19

2022-06-14 12:13 UTC, jacobvjk approved these changes
lgtm

2022-06-15 09:37 UTC, MirijaHa requested changes

2022-06-15 09:37 UTC, MirijaHa commented on DESCRIPTION
> +    person(given = "Mirja",
please remove me from the authors section, otherwise LGTM

2022-06-16 07:03 UTC, MirijaHa approved these changes

2022-06-16 07:04 UTC, merged